# Generated by Django 3.1.2 on 2020-10-24 20:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MA', unique=True),
        ),
    ]
