# Generated by Django 3.1.2 on 2020-10-26 10:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_auto_20201024_2122'),
        ('livre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('plivre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livre.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmddate', models.DateField(verbose_name=datetime.datetime(2020, 10, 26, 10, 55, 34, 775518, tzinfo=utc))),
                ('cmdclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('cmdlivre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livre.livre')),
            ],
        ),
    ]
