# Generated by Django 3.1.2 on 2020-10-27 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0001_initial'),
        ('panier', '0002_auto_20201026_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='cmddate',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 16, 56, 20, 363789, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='commande',
            name='cmdlivre',
        ),
        migrations.AddField(
            model_name='commande',
            name='cmdlivre',
            field=models.ManyToManyField(to='livre.Livre'),
        ),
    ]
