# Generated by Django 3.1.2 on 2020-10-27 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0003_auto_20201027_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='cmddate',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 19, 1, 5, 192690, tzinfo=utc)),
        ),
    ]
