# Generated by Django 3.1.2 on 2020-10-27 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0004_auto_20201027_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='cmddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
