# Generated by Django 3.1.2 on 2020-10-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0001_initial'),
        ('panier', '0005_auto_20201027_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='plivre',
        ),
        migrations.AddField(
            model_name='panier',
            name='plivre',
            field=models.ManyToManyField(to='livre.Livre'),
        ),
    ]
